-- Dataset 3: 1990s Cinema - 100 movies
-- Era of indie films, CGI revolution, and blockbuster franchises

INSERT INTO movie (title, description, release_year, runtime_minutes, director, genre, rating, imdb_rating) VALUES
('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.', 1990, 146, 'Martin Scorsese', 'Crime', 'R', 8.7),
('Dances with Wolves', 'Lieutenant John Dunbar, exiled to a remote western Civil War outpost, befriends wolves and Native Americans, making him an intolerable aberration in the military.', 1990, 181, 'Kevin Costner', 'Adventure', 'PG-13', 8.0),
('Ghost', 'After a young man is murdered, his spirit stays behind to warn his lover of impending danger, with the help of a reluctant psychic.', 1990, 127, 'Jerry Zucker', 'Drama', 'PG-13', 7.1),
('Pretty Woman', 'A man in a legal but hurtful business needs an escort for some social events, and hires a beautiful prostitute he meets.', 1990, 119, 'Garry Marshall', 'Comedy', 'R', 7.1),
('Home Alone', 'An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.', 1990, 103, 'Chris Columbus', 'Comedy', 'PG', 7.7),
('Awakenings', 'The victims of an encephalitis epidemic many years ago have been catatonic ever since, but now a new drug offers the prospect of reviving them.', 1990, 121, 'Penny Marshall', 'Biography', 'PG-13', 7.8),
('The Silence of the Lambs', 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 1991, 118, 'Jonathan Demme', 'Crime', 'R', 8.6),
('Beauty and the Beast', 'A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman''s love.', 1991, 84, 'Gary Trousdale', 'Animation', 'G', 8.0),
('Terminator 2: Judgment Day', 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son from a more advanced and powerful cyborg.', 1991, 137, 'James Cameron', 'Action', 'R', 8.6),
('JFK', 'New Orleans District Attorney Jim Garrison discovers there''s more to the Kennedy assassination than the official story.', 1991, 189, 'Oliver Stone', 'Drama', 'R', 8.0),
('The Fisher King', 'A former radio DJ, suicidally despondent because of a terrible mistake he made, finds redemption in helping a deranged homeless man.', 1991, 137, 'Terry Gilliam', 'Comedy', 'R', 7.5),
('Bugsy', 'The story of how Benjamin Bugsy Siegel started Las Vegas.', 1991, 136, 'Barry Levinson', 'Biography', 'R', 6.8),
('Unforgiven', 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man.', 1992, 131, 'Clint Eastwood', 'Drama', 'R', 8.2),
('The Crying Game', 'A British soldier kidnapped by IRA terrorists soon befriends one of his captors, who then becomes drawn into the soldier''s world.', 1992, 112, 'Neil Jordan', 'Crime', 'R', 7.2),
('A Few Good Men', 'Military lawyer Lieutenant Daniel Kaffee defends Marines accused of murder. They contend they were acting under orders.', 1992, 138, 'Rob Reiner', 'Drama', 'R', 7.7),
('Scent of a Woman', 'A prep school student needing money agrees to babysit a blind man, but the job is not at all what he anticipated.', 1992, 156, 'Martin Brest', 'Drama', 'R', 8.0),
('Howards End', 'A businessman thwarts his wife''s bequest of an estate to another woman.', 1992, 142, 'James Ivory', 'Drama', 'PG', 7.4),
('Aladdin', 'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.', 1992, 90, 'Ron Clements', 'Animation', 'G', 8.0),
('Reservoir Dogs', 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.', 1992, 99, 'Quentin Tarantino', 'Crime', 'R', 8.3),
('Malcolm X', 'Biographical epic of the controversial and influential Black Nationalist leader, from his early life and career as a small-time gangster, to his ministry.', 1992, 202, 'Spike Lee', 'Biography', 'PG-13', 7.7),
('Schindler''s List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 1993, 195, 'Steven Spielberg', 'Biography', 'R', 9.0),
('The Fugitive', 'Dr. Richard Kimble, unjustly accused of murdering his wife, must find the real killer while being the target of a nationwide manhunt led by a seasoned U.S. Marshal.', 1993, 130, 'Andrew Davis', 'Action', 'PG-13', 7.8),
('In the Name of the Father', 'A man''s coerced confession to an IRA bombing he did not commit results in the imprisonment of his father as well.', 1993, 133, 'Jim Sheridan', 'Biography', 'R', 8.1),
('The Piano', 'In the mid-19th century, a mute woman is sent to New Zealand along with her young daughter and prized piano for an arranged marriage.', 1993, 121, 'Jane Campion', 'Drama', 'R', 7.5),
('The Remains of the Day', 'A butler who sacrificed body and soul to service in the years leading up to World War II realizes too late how misguided his loyalty was.', 1993, 134, 'James Ivory', 'Drama', 'PG', 7.8),
('Jurassic Park', 'A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park''s cloned dinosaurs to run loose.', 1993, 127, 'Steven Spielberg', 'Adventure', 'PG-13', 8.2),
('Groundhog Day', 'A narcissistic TV weatherman finds himself stuck in a time loop, reliving the same day over and over again.', 1993, 101, 'Harold Ramis', 'Comedy', 'PG', 8.0),
('The Nightmare Before Christmas', 'Jack Skellington, king of Halloween Town, discovers Christmas Town, but his attempts to bring Christmas to his home causes confusion.', 1993, 76, 'Henry Selick', 'Animation', 'PG', 7.9),
('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 1994, 142, 'Robert Zemeckis', 'Drama', 'PG-13', 8.8),
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 1994, 142, 'Frank Darabont', 'Drama', 'R', 9.3),
('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 1994, 154, 'Quentin Tarantino', 'Crime', 'R', 8.9),
('The Lion King', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 1994, 88, 'Roger Allers', 'Animation', 'G', 8.5),
('Quiz Show', 'A young lawyer, Richard Goodwin, investigates a potentially fixed game show.', 1994, 133, 'Robert Redford', 'Biography', 'PG-13', 7.5),
('Four Weddings and a Funeral', 'Over the course of five social occasions, a committed bachelor must consider the notion that he may have discovered love.', 1994, 117, 'Mike Newell', 'Comedy', 'R', 7.1),
('Speed', 'A young police officer must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph.', 1994, 116, 'Jan de Bont', 'Action', 'R', 7.3),
('Léon: The Professional', 'A professional assassin reluctantly takes a 12-year-old girl under his wing after her family is murdered by a corrupt DEA agent.', 1994, 110, 'Luc Besson', 'Action', 'R', 8.5),
('Braveheart', 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.', 1995, 178, 'Mel Gibson', 'Biography', 'R', 8.3),
('Apollo 13', 'NASA must devise a strategy to return Apollo 13 to Earth safely after the spacecraft undergoes massive internal damage.', 1995, 140, 'Ron Howard', 'Adventure', 'PG', 7.7),
('Sense and Sensibility', 'Rich Mr. Dashwood dies, leaving his second wife and her three daughters poor by the rules of inheritance.', 1995, 136, 'Ang Lee', 'Drama', 'PG', 7.7),
('The Usual Suspects', 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.', 1995, 106, 'Bryan Singer', 'Crime', 'R', 8.5),
('Leaving Las Vegas', 'Ben Sanderson, a Hollywood screenwriter who lost everything because of his alcoholism, arrives in Las Vegas to drink himself to death.', 1995, 111, 'Mike Figgis', 'Drama', 'R', 7.5),
('Casino', 'A tale of greed, deception, money, power, and murder occur between two best friends and a trophy wife over a gambling empire.', 1995, 178, 'Martin Scorsese', 'Crime', 'R', 8.2),
('Se7en', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 1995, 127, 'David Fincher', 'Crime', 'R', 8.6),
('Toy Story', 'A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy''s bedroom.', 1995, 81, 'John Lasseter', 'Animation', 'G', 8.3),
('Heat', 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.', 1995, 170, 'Michael Mann', 'Crime', 'R', 8.3),
('Fargo', 'Minnesota car salesman Jerry Lundegaard''s inept crime falls apart due to his and his henchmen''s bungling and the persistent police work of the quite pregnant Marge Gunderson.', 1996, 98, 'Joel Coen', 'Crime', 'R', 8.1),
('The English Patient', 'At the close of World War II, a young nurse tends to a badly-burned plane crash victim. His past is shown in flashbacks.', 1996, 162, 'Anthony Minghella', 'Drama', 'R', 7.4),
('Shine', 'Pianist David Helfgott, driven by his father and teachers, has a breakdown. Years later he returns to the piano, to popular if not critical acclaim.', 1996, 105, 'Scott Hicks', 'Biography', 'PG-13', 7.7),
('Secrets & Lies', 'A successful black woman discovers that her birth mother is an underprivileged white woman, but the woman denies it.', 1996, 136, 'Mike Leigh', 'Comedy', 'R', 8.0),
('The Rock', 'A mild-mannered chemist and an ex-con must lead the counterstrike when a rogue group of military men, led by a renegade general, threaten a nerve gas attack from Alcatraz.', 1996, 136, 'Michael Bay', 'Action', 'R', 7.4),
('Independence Day', 'The aliens are coming and their goal is to invade and destroy Earth. Fighting superior technology, mankind''s best weapon is the will to survive.', 1996, 145, 'Roland Emmerich', 'Action', 'PG-13', 7.0),
('Scream', 'A year after the murder of her mother, a teenage girl is terrorized by a new killer, who targets the girl and her friends.', 1996, 111, 'Wes Craven', 'Horror', 'R', 7.4),
('Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 1997, 194, 'James Cameron', 'Drama', 'PG-13', 7.9),
('Good Will Hunting', 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.', 1997, 126, 'Gus Van Sant', 'Drama', 'R', 8.3),
('L.A. Confidential', 'As corruption grows in 1950s Los Angeles, three policemen investigate a series of murders with their own brand of justice.', 1997, 138, 'Curtis Hanson', 'Crime', 'R', 8.2),
('As Good as It Gets', 'A single mother and waitress, a misanthropic author, and a gay artist form an unlikely friendship.', 1997, 139, 'James L. Brooks', 'Comedy', 'PG-13', 7.7),
('The Full Monty', 'Six unemployed steel workers form a male striptease act. The women cheer them on to go for the full monty.', 1997, 91, 'Peter Cattaneo', 'Comedy', 'R', 7.2),
('Men in Black', 'A police officer joins a secret organization that polices and monitors extraterrestrial interactions on Earth.', 1997, 98, 'Barry Sonnenfeld', 'Action', 'PG-13', 7.3),
('Life Is Beautiful', 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son.', 1997, 116, 'Roberto Benigni', 'Comedy', 'PG-13', 8.6),
('The Truman Show', 'An insurance salesman discovers his whole life is actually a reality TV show.', 1998, 103, 'Peter Weir', 'Comedy', 'PG', 8.2),
('Saving Private Ryan', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 1998, 169, 'Steven Spielberg', 'Drama', 'R', 8.6),
('Shakespeare in Love', 'A young Shakespeare, out of ideas and short of cash, meets his ideal woman and is inspired to write one of his most famous plays.', 1998, 123, 'John Madden', 'Comedy', 'R', 7.1),
('The Thin Red Line', 'Adaptation of James Jones'' autobiographical 1962 novel, focusing on the conflict at Guadalcanal during the second World War.', 1998, 170, 'Terrence Malick', 'Drama', 'R', 7.6),
('Elizabeth', 'The early years of the reign of Elizabeth I of England and her difficult task of learning what is necessary to be a monarch.', 1998, 124, 'Shekhar Kapur', 'Biography', 'R', 7.4),
('The Big Lebowski', 'Jeff The Dude Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.', 1998, 117, 'Joel Coen', 'Comedy', 'R', 8.1),
('American History X', 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.', 1998, 119, 'Tony Kaye', 'Crime', 'R', 8.5),
('There''s Something About Mary', 'A man gets a chance to meet up with his dream girl from high school, even though his date with her back then was a complete disaster.', 1998, 119, 'Bobby Farrelly', 'Comedy', 'R', 7.1),
('Run Lola Run', 'After a botched money delivery, Lola has 20 minutes to come up with 100,000 Deutschmarks.', 1998, 81, 'Tom Tykwer', 'Action', 'R', 7.6),
('American Beauty', 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter''s best friend.', 1999, 122, 'Sam Mendes', 'Drama', 'R', 8.3),
('The Sixth Sense', 'A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.', 1999, 107, 'M. Night Shyamalan', 'Drama', 'PG-13', 8.2),
('The Green Mile', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', 1999, 189, 'Frank Darabont', 'Crime', 'R', 8.6),
('Being John Malkovich', 'A puppeteer discovers a portal that leads literally into the head of movie star John Malkovich.', 1999, 113, 'Spike Jonze', 'Comedy', 'R', 7.7),
('Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 1999, 139, 'David Fincher', 'Drama', 'R', 8.8),
('The Matrix', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth about his reality.', 1999, 136, 'Lana Wachowski', 'Action', 'R', 8.7),
('The Cider House Rules', 'A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.', 1999, 126, 'Lasse Hallström', 'Drama', 'PG-13', 7.4),
('Magnolia', 'An epic mosaic of interrelated characters in search of love, forgiveness and meaning in the San Fernando Valley.', 1999, 188, 'Paul Thomas Anderson', 'Drama', 'R', 8.0),
('The Insider', 'A research chemist comes under personal and professional attack when he decides to appear in a 60 Minutes exposé on Big Tobacco.', 1999, 157, 'Michael Mann', 'Biography', 'R', 7.8),
('Toy Story 2', 'When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody before he becomes a museum toy property.', 1999, 92, 'John Lasseter', 'Animation', 'G', 7.9),
('Three Kings', 'In the aftermath of the Persian Gulf War, four soldiers set out to steal gold that was stolen from Kuwait.', 1999, 114, 'David O. Russell', 'Action', 'R', 7.1),
('The Talented Mr. Ripley', 'In late 1950s New York, Tom Ripley, a young underachiever, is sent to Italy to retrieve Dickie Greenleaf, a rich and spoiled millionaire playboy.', 1999, 139, 'Anthony Minghella', 'Crime', 'R', 7.4),
('Galaxy Quest', 'The alumni cast of a space opera television series have to play their roles as the real thing when an alien race needs their help.', 1999, 102, 'Dean Parisot', 'Adventure', 'PG', 7.4),
('Election', 'A high school teacher''s personal life becomes complicated as he works with students during the school election.', 1999, 103, 'Alexander Payne', 'Comedy', 'R', 7.3),
('Austin Powers: The Spy Who Shagged Me', 'Dr. Evil is back and has invented a new time machine that allows him to go back to the 1960s and steal Austin Powers'' mojo.', 1999, 95, 'Jay Roach', 'Adventure', 'PG-13', 6.7),
('The Blair Witch Project', 'Three film students vanish after traveling into a Maryland forest to film a documentary on the local Blair Witch legend.', 1999, 81, 'Daniel Myrick', 'Horror', 'R', 6.5),
('Star Wars: Episode I - The Phantom Menace', 'Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force.', 1999, 136, 'George Lucas', 'Action', 'PG', 6.5),
('The Mummy', 'At an archaeological dig in the ancient city of Hamunaptra, an American serving in the French Foreign Legion accidentally awakens a mummy.', 1999, 124, 'Stephen Sommers', 'Action', 'PG-13', 7.1),
('Notting Hill', 'The life of a simple bookshop owner changes when he meets the most famous film star in the world.', 1999, 124, 'Roger Michell', 'Comedy', 'PG-13', 7.2),
('Office Space', 'Three company workers who hate their jobs decide to rebel against their greedy boss.', 1999, 89, 'Mike Judge', 'Comedy', 'R', 7.6),
('The Iron Giant', 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.', 1999, 86, 'Brad Bird', 'Animation', 'PG', 8.1),
('Girl, Interrupted', 'Based on writer Susanna Kaysen''s account of her 18-month stay at a mental hospital in the late 1960s.', 1999, 127, 'James Mangold', 'Biography', 'R', 7.3),
('Double Jeopardy', 'A woman framed for her husband''s murder suspects he is still alive; as she has already been tried for the crime, she can''t be re-prosecuted if she finds and kills him.', 1999, 105, 'Bruce Beresford', 'Crime', 'R', 6.5),
('Sleepy Hollow', 'Ichabod Crane is sent to Sleepy Hollow to investigate the decapitations of three people, with the culprit being the legendary apparition, The Headless Horseman.', 1999, 105, 'Tim Burton', 'Fantasy', 'R', 7.3),
('Analyze This', 'A comedy about a psychiatrist whose number one patient is an insecure mob boss.', 1999, 103, 'Harold Ramis', 'Comedy', 'R', 6.7),
('October Sky', 'The true story of Homer Hickam, a coal miner''s son who was inspired by the first Sputnik launch to take up rocketry against his father''s wishes.', 1999, 108, 'Joe Johnston', 'Biography', 'PG', 7.8),
('The World Is Not Enough', 'James Bond uncovers a nuclear plot while protecting an oil heiress from her former kidnapper, an international terrorist who can''t feel pain.', 1999, 128, 'Michael Apted', 'Action', 'PG-13', 6.4),
('Tarzan', 'A man raised by gorillas must decide where he really belongs when he discovers he is a human.', 1999, 88, 'Chris Buck', 'Animation', 'G', 7.3),
('Wild Wild West', 'The two best special agents in the Wild West must save President Grant from the clutches of a diabolical, wheelchair-bound, steampunk-savvy, Confederate scientist.', 1999, 106, 'Barry Sonnenfeld', 'Action', 'PG-13', 4.9);