-- Movies Dataset 1: Classic Hollywood Era (1930s-1970s)
-- 100 movies with proper SQL escaping

INSERT INTO movie (title, description, release_year, runtime_minutes, director, genre, rating, imdb_rating) VALUES
('Citizen Kane', 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to discover the meaning of his final word.', 1941, 119, 'Orson Welles', 'Drama', 'PG', 8.3),
('Casablanca', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.', 1942, 102, 'Michael Curtiz', 'Drama', 'PG', 8.5),
('The Wizard of Oz', 'Dorothy, a Kansas farm girl, dreams of escaping her mundane life and finds herself in a magical land where she must find the wizard who can help her return home.', 1939, 102, 'Victor Fleming', 'Adventure', 'G', 8.1),
('Gone with the Wind', 'A headstrong Southern belle struggles to survive the Civil War and Reconstruction while clinging to her plantation lifestyle.', 1939, 238, 'Victor Fleming', 'Drama', 'G', 8.1),
('Vertigo', 'A former police detective juggles wrestling with his personal demons and becoming obsessed with a woman who seems to be involved in a mysterious death.', 1958, 128, 'Alfred Hitchcock', 'Mystery', 'PG', 8.3),
('Singing in the Rain', 'A silent film production company transitions to sound films, while a star discovers love with a chorus girl.', 1952, 103, 'Gene Kelly', 'Musical', 'G', 8.3),
('Some Like It Hot', 'After witnessing a mob hit, two musicians disguise themselves as women and join an all-female band to escape the Chicago mafia.', 1959, 121, 'Billy Wilder', 'Comedy', 'Unrated', 8.2),
('North by Northwest', 'A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies.', 1959, 136, 'Alfred Hitchcock', 'Thriller', 'Unrated', 8.3),
('The Third Man', 'Pulp novelist Holly Martins travels to shadowy, postwar Vienna to investigate the mysterious death of his old friend Harry Lime.', 1949, 93, 'Carol Reed', 'Thriller', 'Unrated', 8.1),
('All About Eve', 'A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.', 1950, 138, 'Joseph L. Mankiewicz', 'Drama', 'Unrated', 8.2),
('On the Waterfront', 'An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.', 1954, 108, 'Elia Kazan', 'Crime', 'Unrated', 8.1),
('Sunset Boulevard', 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.', 1950, 110, 'Billy Wilder', 'Drama', 'Unrated', 8.4),
('The Maltese Falcon', 'A private detective becomes involved with a woman seeking to locate a valuable bird statue.', 1941, 100, 'John Huston', 'Mystery', 'Unrated', 8.1),
('Double Indemnity', 'An insurance salesman and a married woman plot to kill her husband for his life insurance.', 1944, 107, 'Billy Wilder', 'Crime', 'Unrated', 8.3),
('The Best Years of Our Lives', 'Three World War II veterans return home to small-town America to discover that they and their families have been irreparably changed.', 1946, 170, 'William Wyler', 'Drama', 'Unrated', 8.1),
('12 Angry Men', 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', 1957, 96, 'Sidney Lumet', 'Drama', 'Approved', 9.0),
('Notorious', 'The daughter of a convicted Nazi spy is asked by American agents to gather information on a ring of Nazi scientists in South America.', 1946, 101, 'Alfred Hitchcock', 'Thriller', 'Unrated', 8.0),
('The Philadelphia Story', 'A rich woman''s ex-husband and a tabloid-type reporter turn up just before her planned remarriage.', 1940, 112, 'George Cukor', 'Comedy', 'Unrated', 7.9),
('It''s a Wonderful Life', 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.', 1946, 130, 'Frank Capra', 'Drama', 'PG', 8.6),
('The Treasure of the Sierra Madre', 'Two Americans searching for gold in Mexico team up with a grizzled prospector.', 1948, 126, 'John Huston', 'Adventure', 'Unrated', 8.2),
('The Bridge on the River Kwai', 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors.', 1957, 161, 'David Lean', 'War', 'PG', 8.1),
('Rear Window', 'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.', 1954, 112, 'Alfred Hitchcock', 'Mystery', 'PG', 8.4),
('Roman Holiday', 'A bored and sheltered princess escapes her guardians and falls in love with an American newsman in Rome.', 1953, 118, 'William Wyler', 'Romance', 'Unrated', 8.0),
('The African Queen', 'In WWI Africa, a gin-swilling riverboat captain is persuaded by a strait-laced missionary to use his boat to attack an enemy warship.', 1951, 105, 'John Huston', 'Adventure', 'Unrated', 7.7),
('A Streetcar Named Desire', 'Disturbed Blanche DuBois moves in with her sister in New Orleans and is tormented by her brutish brother-in-law while her reality crumbles around her.', 1951, 122, 'Elia Kazan', 'Drama', 'PG', 8.0),
('Lawrence of Arabia', 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I.', 1962, 228, 'David Lean', 'Biography', 'PG', 8.3),
('To Kill a Mockingbird', 'A lawyer''s advice to his children as he defends the real mockingbird of Harper Lee''s classic novel.', 1962, 129, 'Robert Mulligan', 'Drama', 'Unrated', 8.2),
('Dr. Strangelove', 'An insane general triggers a path to nuclear holocaust that a War Room full of politicians and generals frantically tries to stop.', 1964, 95, 'Stanley Kubrick', 'Comedy', 'PG', 8.4),
('The Apartment', 'A man tries to rise in his company by letting its executives use his apartment for trysts, only to be discovered by the girl he loves.', 1960, 125, 'Billy Wilder', 'Comedy', 'Unrated', 8.3),
('The Great Escape', 'Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II.', 1963, 172, 'John Sturges', 'Adventure', 'Unrated', 8.2),
('Psycho', 'A Phoenix secretary embezzles money and runs off to a remote motel run by a disturbed man under the domination of his mother.', 1960, 109, 'Alfred Hitchcock', 'Horror', 'R', 8.5),
('West Side Story', 'Two youngsters from rival New York gangs fall in love, but tensions between their respective friends build toward tragedy.', 1961, 153, 'Robert Wise', 'Musical', 'Unrated', 7.5),
('The Magnificent Seven', 'Seven gunfighters are hired by Mexican peasants to liberate their village from oppressive bandits.', 1960, 128, 'John Sturges', 'Western', 'Unrated', 7.7),
('Ben-Hur', 'After a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge.', 1959, 212, 'William Wyler', 'Adventure', 'G', 8.1),
('Spartacus', 'The rebellious Thracian Spartacus, born and raised a slave, is sold to Gladiator trainer Batiatus.', 1960, 197, 'Stanley Kubrick', 'Biography', 'PG-13', 7.9),
('The Hustler', 'An up-and-coming pool player plays a legendary champion in a single high-stakes match.', 1961, 134, 'Robert Rossen', 'Drama', 'Unrated', 7.9),
('Inherit the Wind', 'Based on a real-life case in 1925, two great lawyers argue the case for and against a science teacher accused of the crime of teaching evolution.', 1960, 128, 'Stanley Kramer', 'Drama', 'Unrated', 8.1),
('The Man Who Shot Liberty Valance', 'A senator returns to a western town for the funeral of an old friend and tells the story of his origins.', 1962, 123, 'John Ford', 'Western', 'Unrated', 8.1),
('The Birds', 'A wealthy San Francisco socialite pursues a potential boyfriend to a small Northern California town that slowly takes a turn for the bizarre.', 1963, 119, 'Alfred Hitchcock', 'Horror', 'PG-13', 7.7),
('Judgment at Nuremberg', 'In 1948, an American court in occupied Germany tries four Nazi judges for war crimes.', 1961, 186, 'Stanley Kramer', 'Drama', 'Unrated', 8.2),
('The Manchurian Candidate', 'An ex-prisoner of war is brainwashed as an unwitting assassin for an international Communist conspiracy.', 1962, 126, 'John Frankenheimer', 'Thriller', 'PG-13', 7.9),
('Lolita', 'A middle-aged college professor becomes infatuated with the teenage daughter of his landlady.', 1962, 153, 'Stanley Kubrick', 'Crime', 'Unrated', 7.5),
('What Ever Happened to Baby Jane?', 'A former child star torments her paraplegic sister in their decaying Hollywood mansion.', 1962, 134, 'Robert Aldrich', 'Drama', 'Unrated', 8.0),
('The Sound of Music', 'A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.', 1965, 174, 'Robert Wise', 'Biography', 'G', 8.0),
('My Fair Lady', 'A misogynistic and snobbish phonetics professor agrees to a wager that he can take a flower girl and make her presentable in high society.', 1964, 170, 'George Cukor', 'Drama', 'G', 7.8),
('Goldfinger', 'While investigating a gold magnate''s smuggling, James Bond uncovers a plot to contaminate the Fort Knox gold reserve.', 1964, 110, 'Guy Hamilton', 'Action', 'PG', 7.7),
('Mary Poppins', 'In turn of the century London, a magical nanny employs music and adventure to help two neglected children become closer to their father.', 1964, 139, 'Robert Stevenson', 'Comedy', 'G', 7.8),
('Who''s Afraid of Virginia Woolf?', 'A bitter aging couple with the help of alcohol, use a young couple to fuel anguish and emotional pain towards each other.', 1966, 131, 'Mike Nichols', 'Drama', 'Unrated', 8.0),
('Bonnie and Clyde', 'Bored waitress Bonnie Parker falls in love with an ex-con named Clyde Barrow and together they start a violent crime spree.', 1967, 111, 'Arthur Penn', 'Biography', 'R', 7.8),
('The Graduate', 'A disillusioned college graduate finds himself torn between his older lover and her daughter.', 1967, 106, 'Mike Nichols', 'Comedy', 'PG', 8.0),
('In the Heat of the Night', 'A black police detective from Philadelphia becomes involved in a murder case in a racist small town in Mississippi.', 1967, 110, 'Norman Jewison', 'Crime', 'Unrated', 7.9),
('Cool Hand Luke', 'A laid back Southern man is sentenced to two years in a rural prison, but refuses to conform.', 1967, 127, 'Stuart Rosenberg', 'Crime', 'Unrated', 8.1),
('Guess Who''s Coming to Dinner', 'A couple''s attitudes are challenged when their daughter brings home a fiancé who is black.', 1967, 108, 'Stanley Kramer', 'Comedy', 'Unrated', 7.8),
('Planet of the Apes', 'An astronaut crew crash-lands on a planet in the distant future where intelligent talking apes are the dominant species.', 1968, 112, 'Franklin J. Schaffner', 'Adventure', 'G', 8.0),
('2001: A Space Odyssey', 'Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000.', 1968, 149, 'Stanley Kubrick', 'Sci-Fi', 'G', 8.3),
('The Odd Couple', 'A New Yorker newly separated from his wife moves in with his best friend, a divorced sportswriter, but their ideas of housekeeping and lifestyles are as different as night and day.', 1968, 105, 'Gene Saks', 'Comedy', 'G', 7.7),
('Rosemary''s Baby', 'A young couple moves into an apartment building where the wife becomes surrounded by odd neighbors and occurrences.', 1968, 137, 'Roman Polanski', 'Drama', 'R', 8.0),
('Butch Cassidy and the Sundance Kid', 'Wyoming, early 1900s. Butch Cassidy and The Sundance Kid are the leaders of a band of outlaws.', 1969, 110, 'George Roy Hill', 'Biography', 'PG', 8.1),
('Easy Rider', 'Two bikers head from Los Angeles to New Orleans through the open country and desert lands.', 1969, 95, 'Dennis Hopper', 'Adventure', 'R', 7.3),
('Midnight Cowboy', 'A naive hustler travels from Texas to New York City to seek personal fortune, finding a new friend in the process.', 1969, 113, 'John Schlesinger', 'Drama', 'R', 7.8),
('The Wild Bunch', 'An aging group of outlaws look for one last big score as the traditional American West is disappearing around them.', 1969, 145, 'Sam Peckinpah', 'Action', 'R', 7.9),
('True Grit', 'A drunken, hard-nosed U.S. Marshal and a Texas Ranger help a stubborn teenager track down her father''s murderer in Indian Territory.', 1969, 128, 'Henry Hathaway', 'Adventure', 'G', 7.4),
('They Shoot Horses, Don''t They?', 'The lives of a disparate group of contestants intertwine in an inhumanely grueling dance marathon.', 1969, 120, 'Sydney Pollack', 'Drama', 'PG', 7.9),
('Hello, Dolly!', 'Matchmaker Dolly Levi travels to Yonkers to find a partner for half-a-millionaire Horace Vandergelder.', 1969, 146, 'Gene Kelly', 'Adventure', 'G', 7.0),
('The French Connection', 'A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection.', 1971, 104, 'William Friedkin', 'Action', 'R', 7.7),
('A Clockwork Orange', 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it does not go as planned.', 1971, 136, 'Stanley Kubrick', 'Crime', 'R', 8.3),
('The Last Picture Show', 'A group of teenagers in a small Texas town face their own choices as their elders become wistful about their past.', 1971, 118, 'Peter Bogdanovich', 'Drama', 'R', 8.0),
('Dirty Harry', 'When a madman calling himself the Scorpio Killer menaces San Francisco, tough-as-nails Police Inspector Harry Callahan is assigned to track down the crazed psychopath.', 1971, 102, 'Don Siegel', 'Action', 'R', 7.7),
('Klute', 'A small-town detective searching for a missing man has only one lead: a connection with a New York prostitute.', 1971, 114, 'Alan J. Pakula', 'Crime', 'R', 7.1),
('Fiddler on the Roof', 'In pre-revolutionary Russia, a Jewish peasant contends with marrying off three of his daughters while growing anti-Semitic sentiment threatens his village.', 1971, 181, 'Norman Jewison', 'Drama', 'G', 8.0),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 1972, 175, 'Francis Ford Coppola', 'Crime', 'R', 9.2),
('Cabaret', 'A female girlie club entertainer in Weimar Republic era Berlin romances two men while the Nazi Party rises to power around them.', 1972, 124, 'Bob Fosse', 'Drama', 'PG', 7.8),
('Deliverance', 'Intent on seeing the Cahulawassee River before it''s dammed and turned into a lake, outdoor fanatic Lewis Medlock takes his friends on a canoeing trip they''ll never forget.', 1972, 109, 'John Boorman', 'Adventure', 'R', 7.7),
('The Poseidon Adventure', 'A group of passengers struggle to survive and escape when their ocean liner completely capsizes at sea.', 1972, 117, 'Ronald Neame', 'Action', 'PG', 7.1),
('Sounder', 'The oldest son of a loving and strong family of black sharecroppers comes of age in the Depression-era South after his father is imprisoned for stealing food.', 1972, 105, 'Martin Ritt', 'Drama', 'G', 7.6),
('The Candidate', 'Bill McKay is a candidate for the U.S. Senate from California. He has no hope of winning, so he is willing to tweak the establishment.', 1972, 110, 'Michael Ritchie', 'Comedy', 'PG', 7.0),
('The Heartbreak Kid', 'A newlywed man who believes he''s just gotten hitched to the perfect woman encounters another lady on his honeymoon.', 1972, 106, 'Elaine May', 'Comedy', 'PG', 7.0),
('Lady Sings the Blues', 'The story of the troubled life and career of the legendary jazz singer, Billie Holiday.', 1972, 144, 'Sidney J. Furie', 'Biography', 'R', 7.0),
('What''s Up, Doc?', 'The accidental mix-up of four identical plaid overnight bags leads to a series of increasingly wild and wacky situations.', 1972, 94, 'Peter Bogdanovich', 'Comedy', 'G', 7.7),
('The Exorcist', 'When a teenage girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.', 1973, 122, 'William Friedkin', 'Horror', 'R', 8.0),
('The Sting', 'Two grifters team up to pull off the ultimate con.', 1973, 129, 'George Roy Hill', 'Comedy', 'PG', 8.3),
('American Graffiti', 'A group of teenagers in California''s central valley spend one final night after their 1962 high school graduation cruising the strip with their buddies.', 1973, 110, 'George Lucas', 'Comedy', 'PG', 7.4),
('Serpico', 'The true story of Frank Serpico, the cop who couldn''t be bought.', 1973, 130, 'Sidney Lumet', 'Biography', 'R', 7.7),
('Paper Moon', 'During the Great Depression, a con man finds himself saddled with a young girl who may or may not be his daughter.', 1973, 102, 'Peter Bogdanovich', 'Comedy', 'PG', 8.1),
('Enter the Dragon', 'A martial artist agrees to spy on a reclusive crime lord using his invitation to a tournament there as cover.', 1973, 102, 'Robert Clouse', 'Action', 'R', 7.7),
('The Way We Were', 'Two desperate people have a wonderful romance, but their political views and convictions drive them apart.', 1973, 118, 'Sydney Pollack', 'Drama', 'PG', 7.0),
('Save the Tiger', 'The story of a businessman who struggles with the ethnic and ideological diversity of contemporary life.', 1973, 100, 'John G. Avildsen', 'Drama', 'R', 6.9),
('The Last Detail', 'Two Navy men are ordered to bring a young offender to prison, but decide to show him one last good time along the way.', 1973, 104, 'Hal Ashby', 'Comedy', 'R', 7.5),
('A Touch of Class', 'Romantic comedy about a widow who falls for a married American insurance executive visiting London on business.', 1973, 106, 'Melvin Frank', 'Comedy', 'PG', 6.5),
('The Godfather Part II', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 1974, 202, 'Francis Ford Coppola', 'Crime', 'R', 9.0),
('Chinatown', 'A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.', 1974, 130, 'Roman Polanski', 'Drama', 'R', 8.2),
('The Conversation', 'A paranoid, secretive surveillance expert has a crisis of conscience when he suspects that the couple he is spying on will be murdered.', 1974, 113, 'Francis Ford Coppola', 'Drama', 'PG', 7.8),
('Blazing Saddles', 'A town where everyone seems to be named Johnson is in the way of the railroad and, in order to grab their land, Hedley Lemar sends the toughest gang he can find.', 1974, 93, 'Mel Brooks', 'Comedy', 'R', 7.7),
('Young Frankenstein', 'An American grandson of the infamous scientist, struggling to prove that his grandfather was not as insane as people believe, is invited to Transylvania.', 1974, 106, 'Mel Brooks', 'Comedy', 'PG', 8.0),
('The Towering Inferno', 'At the opening party of a collosal, but poorly constructed, office building, a massive fire breaks out that threatens to destroy the tower and everyone in it.', 1974, 165, 'John Guillermin', 'Action', 'PG', 7.0),
('Murder on the Orient Express', 'In December 1935, when his train is stopped by deep snow, detective Hercule Poirot is called on to solve a murder that occurred in his car the night before.', 1974, 128, 'Sidney Lumet', 'Crime', 'PG', 7.3),
('Alice Doesn''t Live Here Anymore', 'A recently widowed woman is on the road with her precocious young son, determined to make a new life for herself as a singer.', 1974, 112, 'Martin Scorsese', 'Drama', 'PG', 7.3),
('Lenny', 'The story of acerbic 1960s comic Lenny Bruce, whose groundbreaking, no-holds-barred style and social commentary was often deemed by the establishment as too obscene for the public.', 1974, 111, 'Bob Fosse', 'Biography', 'R', 7.6),
('The Apprenticeship of Duddy Kravitz', 'In a quest to fulfill his grandfather''s expectations, Duddy Kravitz, a brash, restless young Jewish man will stop at nothing to buy land.', 1974, 120, 'Ted Kotcheff', 'Comedy', 'PG', 6.8),
('Harry and Tonto', 'When his apartment building is torn down, a retired lifelong New Yorker goes on a cross country odyssey with his beloved cat Tonto.', 1974, 115, 'Paul Mazursky', 'Comedy', 'R', 7.4),
('The Front Page', 'A ruthless editor tries to get his star reporter to postpone his retirement.', 1974, 105, 'Billy Wilder', 'Comedy', 'PG', 7.3),
('Daisy Miller', 'In this comedy of manners, Frederick Winterbourne tries to figure out the bright and bubbly Daisy Miller, only to be helped and hindered by false judgments from their fellow friends.', 1974, 91, 'Peter Bogdanovich', 'Comedy', 'G', 6.1);