"""add date_of_birth to member

Revision ID: 39dae670e7e8
Revises: 
Create Date: 2025-10-08 22:50:33.163941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dae670e7e8'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('member', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # Set default for existing records
    op.execute("UPDATE member SET date_of_birth = '1900-01-01' WHERE date_of_birth IS NULL")
    # Make it NOT NULL after setting defaults
    op.alter_column('member', 'date_of_birth', nullable=False)

def downgrade():
    op.drop_column('member', 'date_of_birth')

"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('watchlist_member_id_movie_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('watchlist_member_id_movie_id_key'), ['member_id', 'movie_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
"""
